package com.example.padautosolver;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.widget.*;import android.view.*;import org.json.*;import java.io.*;
public final class InventoryActivity extends Activity {
 private LinearLayout root;private InventoryRepository repo;private int offset;
 @Override public void onCreate(Bundle b){super.onCreate(b);render();}
 private void render(){try{repo=new InventoryRepository(this);ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(android.widget.LinearLayout.VERTICAL);root.setPadding(20,20,20,20);scroll.addView(root);setContentView(scroll);
  label("BOX_SCAN・所持一覧",24);label("記録 "+repo.items.length()+" / 不明 "+repo.inventory.optInt("uncertainCount")+"\n走査候補: "+repo.inventory.optBoolean("traversalComplete")+"・検査完了: "+repo.inventory.optBoolean("completeScan")+"\n"+repo.inventory.optString("stopReason"),14);
  button("キャリブレーション・開始前確認",()->calibrate());
  button("カタログJSONをインポート",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,42);});
  button("inventory JSONをDownloadへ保存",()->{try{String path=InventoryExport.saveJson(this);new AlertDialog.Builder(this).setMessage(path).setPositiveButton("OK",null).show();}catch(Exception e){error(e);}});
  button("inventory JSONを共有",()->{try{File f=new File(repo.root,"box_inventory.json");android.net.Uri uri=androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(Intent.ACTION_SEND).setType("application/json").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"所持一覧を共有"));}catch(Exception e){error(e);}});
  button("診断ZIPを端末のDownloadへ保存",()->{
   Toast.makeText(this,"保存中…走査は停止した状態でお待ちください",Toast.LENGTH_LONG).show();
   new Thread(()->{try{String path=InventoryExport.save(getApplicationContext());runOnUiThread(()->new AlertDialog.Builder(this).setMessage(path).setPositiveButton("OK",null).show());}catch(Exception e){runOnUiThread(()->error(e));}},"inventory-export").start();
  });
  button("保存済みページから再集計",()->{
   TextView progress=new TextView(this);progress.setText("再集計中…");AlertDialog dialog=new AlertDialog.Builder(this).setView(progress).setCancelable(false).show();
   new Thread(()->{try{String result=InventoryReplay.rebuild(getApplicationContext(),message->runOnUiThread(()->progress.setText(message)));runOnUiThread(()->{dialog.dismiss();render();new AlertDialog.Builder(this).setMessage(result).setPositiveButton("OK",null).show();});}catch(Exception e){runOnUiThread(()->{dialog.dismiss();error(e);});}},"inventory-replay").start();
  });
  button("前の20件",()->{offset=Math.max(0,offset-20);render();});button("次の20件",()->{offset=Math.min(Math.max(0,repo.items.length()-1),offset+20);render();});
  for(int index=offset;index<Math.min(offset+20,repo.items.length());index++){final int at=index;JSONObject item=repo.items.getJSONObject(index);String path=item.getJSONObject("recognition").optString("evidence").split(";")[0];ImageView icon=new ImageView(this);Bitmap bitmap=BitmapFactory.decodeFile(new File(repo.root,path).getPath());icon.setImageBitmap(bitmap);root.addView(icon,new LinearLayout.LayoutParams(180,180));label("#"+(index+1)+" "+(item.isNull("monsterId")?"unknown":item.optInt("monsterId"))+" "+(item.isNull("name")?"未同定":item.optString("name"))+" / "+item.optString("detailStatus"),15);if(item.has("observedIdentity")){JSONObject observed=item.getJSONObject("observedIdentity");label("詳細OCR候補: No."+(observed.isNull("monsterId")?"未読":observed.optInt("monsterId"))+" "+(observed.isNull("name")?"名前未読":observed.optString("name"))+"（未確認）",14);}
  button("この個体の番号・名前を確認",()->confirm(at));button("この個体の詳細を撮影対象にする",()->{getSharedPreferences("pad_solver",0).edit().putInt("box.detailIndex",at).putString("operationMode","BOX_SCAN").apply();new AlertDialog.Builder(this).setMessage("ゲームでこの個体の詳細を開き、BOXパネルの「詳細を記録」を押してください。スキル・覚醒・潜在はタブごとに記録できます。番号・形態を確認するまで編成へ使いません。").setPositiveButton("OK",null).show();});}
  button("全走査の人手照合を記録",()->{try{if(!repo.inventory.optBoolean("traversalComplete")||repo.inventory.optInt("uncertainCount")>0)throw new Exception("末尾・所持数一致・不明個体の確認が終わっていません");new AlertDialog.Builder(this).setMessage("先頭〜末尾と全個体をゲームのBOXに照合しましたか？候補の育成状態や助っ人は別途確認が必要です。").setPositiveButton("照合済み",(d,w)->{try{repo.inventory.put("humanReconciled",true);repo.save();render();}catch(Exception e){error(e);}}).setNegativeButton("戻る",null).show();}catch(Exception e){error(e);}});
 }catch(Exception e){error(e);}}
 private void confirm(int at){LinearLayout fields=new LinearLayout(this);fields.setOrientation(android.widget.LinearLayout.VERTICAL);EditText id=new EditText(this);id.setHint("ゲーム詳細のNo.");id.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);EditText name=new EditText(this);name.setHint("正確な名前・進化形態");fields.addView(id);fields.addView(name);new AlertDialog.Builder(this).setTitle("実際の詳細画面と照合").setView(fields).setPositiveButton("確認して保存",(d,w)->{try{repo.confirm(at,Integer.parseInt(id.getText().toString()),name.getText().toString());render();}catch(Exception e){error(e);}}).setNegativeButton("不明のまま",null).show();}
 private void calibrate(){android.content.SharedPreferences prefs=getSharedPreferences("pad_solver",0);LinearLayout box=new LinearLayout(this);box.setOrientation(android.widget.LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(box);String[] keys={"columns","expected","firstX","pitchX","top","bottom","pitchY","iconWidth"};String[] names={"列数","所持数（画面の実数）","先頭列中心X/幅","列間隔/幅","上端Y/高さ","下端Y/高さ","行間隔/高さ","アイコン幅/画面幅"};String[] defaults={"5","707","0.094","0.183","0.36","0.875","0.0874","0.145"};EditText[] fields=new EditText[8];for(int i=0;i<8;i++){TextView l=new TextView(this);l.setText(names[i]);box.addView(l);fields[i]=new EditText(this);fields[i].setInputType(8194);fields[i].setText(i<2?String.valueOf(prefs.getInt("box."+keys[i],Integer.parseInt(defaults[i]))):String.valueOf(prefs.getFloat("box."+keys[i],Float.parseFloat(defaults[i]))));box.addView(fields[i]);}CheckBox top=new CheckBox(this);top.setText("BOX先頭にいることを確認した");box.addView(top);CheckBox filters=new CheckBox(this);filters.setText("ALL・検索空欄・絞り込みなしを確認した");box.addView(filters);
 new AlertDialog.Builder(this).setTitle("BOXキャリブレーション（属性順可）").setView(scroll).setPositiveButton("保存",(d,w)->{try{android.content.SharedPreferences.Editor e=prefs.edit();for(int i=0;i<8;i++)if(i<2)e.putInt("box."+keys[i],Integer.parseInt(fields[i].getText().toString()));else e.putFloat("box."+keys[i],Float.parseFloat(fields[i].getText().toString()));e.putBoolean("box.topConfirmed",top.isChecked()).putBoolean("box.filtersConfirmed",filters.isChecked()).apply();new BoxCalibration(prefs).validate();Toast.makeText(this,"保存しました。BOXモードで画面共有を開始してください",Toast.LENGTH_LONG).show();}catch(Exception e){error(e);}}).setNegativeButton("閉じる",null).show();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=42||result!=RESULT_OK||data==null)return;try(InputStream in=getContentResolver().openInputStream(data.getData())){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))>0){if(out.size()+n>8_000_000)throw new IOException("カタログは8MB以下");out.write(buffer,0,n);}JSONObject raw=new JSONObject(out.toString("UTF-8"));MonsterCatalogProvider.Local catalog=new MonsterCatalogProvider.Local(raw);repo.inventory.put("catalogVersion",catalog.getVersion());for(int i=0;i<repo.items.length();i++){JSONObject item=repo.items.getJSONObject(i);java.util.List<Integer> ids=catalog.identify(Long.parseUnsignedLong(item.getString("iconHash"),16));JSONArray candidates=new JSONArray();for(int id:ids)candidates.put(new JSONObject().put("monsterId",id).put("score",.5));item.getJSONObject("recognition").put("candidates",candidates);}try(FileOutputStream f=new FileOutputStream(new File(repo.root,"catalog_version.json"))){f.write(raw.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));}repo.save();render();}catch(Exception e){error(e);}}
 private void label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);root.addView(t);}private void button(String s,Runnable run){Button b=new Button(this);b.setText(s);root.addView(b);b.setOnClickListener(v->run.run());}private void error(Exception e){new AlertDialog.Builder(this).setMessage(e.getMessage()).setPositiveButton("OK",null).show();}
}
