package com.example.padautosolver;
import android.content.Context;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
public final class InventoryRepository {
 final File root; final JSONObject inventory; final JSONArray items;
 InventoryRepository(Context c)throws Exception{root=new File(c.getFilesDir(),"inventory");root.mkdirs();File f=new File(root,"box_inventory.json");inventory=f.isFile()?new JSONObject(new String(java.nio.file.Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8)):new JSONObject();items=inventory.optJSONArray("items")!=null?inventory.getJSONArray("items"):new JSONArray();}
 static InventoryRepository begin(Context c,BoxCalibration config)throws Exception{InventoryRepository r=new InventoryRepository(c);if(r.inventory.has("scanSessionId")){r.session().mkdirs();try(FileOutputStream old=new FileOutputStream(new File(r.session(),"summary.json"))){old.write(r.inventory.toString(2).getBytes(StandardCharsets.UTF_8));}}java.util.List<String> keys=new java.util.ArrayList<>();r.inventory.keys().forEachRemaining(keys::add);for(String key:keys)r.inventory.remove(key);while(r.items.length()>0)r.items.remove(r.items.length()-1);r.inventory.put("schemaVersion",1).put("scanSessionId",UUID.randomUUID().toString()).put("catalogVersion","none").put("completeScan",false).put("traversalComplete",false).put("scannedAt",java.time.Instant.now().toString()).put("expectedCount",config.expected).put("items",r.items).put("scanStartEvidence","user-confirmed top, ALL, no filter");r.save();return r;}
 File session(){return new File(root,"scan_sessions/"+inventory.optString("scanSessionId","none"));}
 synchronized void save()throws Exception{
  // OCR observations have no calibrated confidence. Keep their ranking score at zero.
  for(int i=0;i<items.length();i++){JSONArray candidates=items.getJSONObject(i).getJSONObject("recognition").optJSONArray("candidates");if(candidates!=null)for(int j=0;j<candidates.length();j++){JSONObject candidate=candidates.getJSONObject(j);if("detail_ocr_consensus".equals(candidate.optString("source"))&&!candidate.has("score"))candidate.put("score",0);}}
  int unknown=0;for(int i=0;i<items.length();i++)if(!items.getJSONObject(i).getJSONObject("recognition").optBoolean("userConfirmed"))unknown++;inventory.put("uncertainCount",unknown).put("items",items);File tmp=new File(root,"box_inventory.json.tmp");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(inventory.toString(2).getBytes(StandardCharsets.UTF_8));o.getFD().sync();}java.nio.file.Files.move(tmp.toPath(),new File(root,"box_inventory.json").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}
 void add(int page,int cell,String image,long hash)throws Exception{JSONObject recognition=new JSONObject().put("confidence",0).put("userConfirmed",false).put("candidates",new JSONArray()).put("evidence",image);JSONObject item=new JSONObject().put("instanceId",inventory.getString("scanSessionId")+":"+items.length()).put("monsterId",JSONObject.NULL).put("name",JSONObject.NULL).put("formId",JSONObject.NULL).put("sourcePage",page).put("sourceCell",cell).put("iconHash",Long.toUnsignedString(hash,16)).put("recognition",recognition).put("detailStatus","not_inspected");items.put(item);}
 void confirm(int index,int id,String name)throws Exception{if(id<1||name.trim().isEmpty())throw new IllegalArgumentException("番号と名前を入力してください");JSONObject item=items.getJSONObject(index);item.put("monsterId",id).put("name",name).getJSONObject("recognition").put("userConfirmed",true).put("evidence",item.getJSONObject("recognition").optString("evidence")+"; user identity confirmation");save();}
}
