package com.example.padautosolver;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.widget.*;import android.view.*;import org.json.*;import java.io.*;
public final class InventoryActivity extends Activity {
 private LinearLayout root;private InventoryRepository repo;private int offset;private String query="";private boolean inspectOnly,advanced;
 private java.util.Map<String,JSONObject> reviews=new java.util.HashMap<>();private JSONObject reviewBundle;
 @Override public void onCreate(Bundle b){super.onCreate(b);render();}
 private void render(){try{repo=new InventoryRepository(this);ScrollView scroll=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(android.widget.LinearLayout.VERTICAL);root.setPadding(20,20,20,20);scroll.addView(root);setContentView(scroll);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(scroll,(view,insets)->{androidx.core.graphics.Insets bars=insets.getInsets(androidx.core.view.WindowInsetsCompat.Type.systemBars());root.setPadding(20,20+bars.top,20,20+bars.bottom);return insets;});
  loadReviews();label("BOX_SCAN・所持一覧",24);int captured=0,numbered=0,confirmed=0,inspectCount=0;for(int i=0;i<repo.items.length();i++){JSONObject item=repo.items.getJSONObject(i);if(item.optJSONArray("detailEvidence")!=null&&item.getJSONArray("detailEvidence").length()>0)captured++;JSONObject identity=item.optJSONObject("observedIdentity");if(identity!=null&&!identity.isNull("monsterId"))numbered++;if(item.getJSONObject("recognition").optBoolean("userConfirmed"))confirmed++;JSONObject r=reviews.get(item.getString("instanceId"));if(r!=null&&r.optBoolean("inspectNext"))inspectCount++;}
  label("詳細画像 "+captured+" / "+repo.items.length()+"枠・一覧末尾 "+(repo.inventory.optBoolean("visualEndReached")?"到達":"未確認")+"\n番号OCR候補 "+numbered+"・画像照合案 "+reviews.size()+"\n利用者が番号・名前を確定 "+confirmed+" / "+repo.items.length()+"（育成・スキルは別途検査）",14);
  if(reviewBundle!=null&&reviewBundle.has("countReconciliation")){JSONObject count=reviewBundle.getJSONObject("countReconciliation");label("画像照合の内訳案：所持 "+count.getInt("displayedBoxCount")+"体 ＋ スタック素材 "+count.getJSONArray("stackedInstanceIds").length()+"枠\n編成・個体情報の確定とは別です",14);}
  if(captured>0)label(repo.inventory.optString("detailStopReason"),14);
  button("画像照合JSONを取り込む",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,43);});
  button((inspectOnly?"全個体を表示":"追加検査候補だけ表示（"+inspectCount+"枠）"),()->{inspectOnly=!inspectOnly;offset=0;render();});
  button("検索："+(query.isEmpty()?"番号・名前・#枠番号":query),()->search());
  button(advanced?"データ出力・BOX設定を閉じる":"データ出力・BOX設定",()->{advanced=!advanced;render();});
  if(advanced){button("キャリブレーション・開始前確認",()->calibrate());
  button("カタログJSONをインポート",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,42);});
  button("inventory JSONをDownloadへ保存",()->{try{String path=InventoryExport.saveJson(this);new AlertDialog.Builder(this).setMessage(path).setPositiveButton("OK",null).show();}catch(Exception e){error(e);}});
  button("inventory JSONを共有",()->{try{File f=new File(repo.root,"box_inventory.json");android.net.Uri uri=androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(Intent.ACTION_SEND).setType("application/json").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"所持一覧を共有"));}catch(Exception e){error(e);}});
  button("診断ZIPを端末のDownloadへ保存",()->{
   Toast.makeText(this,"保存中…走査は停止した状態でお待ちください",Toast.LENGTH_LONG).show();
   new Thread(()->{try{String path=InventoryExport.save(getApplicationContext());runOnUiThread(()->new AlertDialog.Builder(this).setMessage(path).setPositiveButton("OK",null).show());}catch(Exception e){runOnUiThread(()->error(e));}},"inventory-export").start();
  });
  button("保存済みページから再集計",()->{
   TextView progress=new TextView(this);progress.setText("再集計中…");AlertDialog dialog=new AlertDialog.Builder(this).setView(progress).setCancelable(false).show();
   new Thread(()->{try{String result=InventoryReplay.rebuild(getApplicationContext(),message->runOnUiThread(()->progress.setText(message)));runOnUiThread(()->{dialog.dismiss();render();new AlertDialog.Builder(this).setMessage(result).setPositiveButton("OK",null).show();});}catch(Exception e){runOnUiThread(()->{dialog.dismiss();error(e);});}},"inventory-replay").start();
  });
  }
  button("前の20件",()->{offset=Math.max(0,offset-20);render();});button("次の20件",()->{offset=Math.min(Math.max(0,repo.items.length()-1),offset+20);render();});
  java.util.List<Integer> visible=new java.util.ArrayList<>();for(int i=0;i<repo.items.length();i++){JSONObject item=repo.items.getJSONObject(i),review=reviews.get(item.getString("instanceId"));if(inspectOnly&&(review==null||!review.optBoolean("inspectNext")))continue;if(!InventorySearch.matches(query,i+1,item,review))continue;visible.add(i);}offset=Math.min(offset,Math.max(0,((visible.size()-1)/20)*20));label("該当 "+visible.size()+"枠（"+(visible.isEmpty()?0:offset+1)+"〜"+Math.min(offset+20,visible.size())+"）",14);
  for(int position=offset;position<Math.min(offset+20,visible.size());position++){int index=visible.get(position);final int at=index;JSONObject item=repo.items.getJSONObject(index);String path=item.getJSONObject("recognition").optString("evidence").split(";")[0];ImageView icon=new ImageView(this);Bitmap bitmap=BitmapFactory.decodeFile(new File(repo.root,path).getPath());icon.setImageBitmap(bitmap);root.addView(icon,new LinearLayout.LayoutParams(180,180));label("#"+(index+1)+" "+(item.isNull("monsterId")?"番号未確定":item.optInt("monsterId"))+" "+(item.isNull("name")?"名前未確定":item.optString("name")),15);JSONObject review=reviews.get(item.getString("instanceId"));if(review!=null){label("画像照合案：No."+review.getInt("monsterId")+" "+(review.isNull("name")?"名前未確認":review.optString("name"))+"（未確定）",16);if(review.optBoolean("inspectNext"))label("追加検査："+review.optString("reason"),14);}else if(item.has("observedIdentity")){JSONObject observed=item.getJSONObject("observedIdentity");label("詳細OCR候補: No."+(observed.isNull("monsterId")?"未読":observed.optInt("monsterId"))+" "+(observed.isNull("name")?"名前未読":observed.optString("name"))+"（未確認）",14);}
  button("保存済みの詳細画像を確認",()->showEvidence(at));
  button("この個体の番号・名前を確認",()->confirm(at));button("この個体の詳細を撮影対象にする",()->{getSharedPreferences("pad_solver",0).edit().putInt("box.detailIndex",at).putString("operationMode","BOX_SCAN").apply();new AlertDialog.Builder(this).setMessage("ゲームでこの個体の詳細を開き、BOXパネルの「詳細を記録」を押してください。スキル・覚醒・潜在はタブごとに記録できます。番号・形態を確認するまで編成へ使いません。").setPositiveButton("OK",null).show();});}
  button("全走査の人手照合を記録",()->{try{if(!repo.inventory.optBoolean("traversalComplete")||repo.inventory.optInt("uncertainCount")>0)throw new Exception("末尾・所持数一致・不明個体の確認が終わっていません");new AlertDialog.Builder(this).setMessage("先頭〜末尾と全個体をゲームのBOXに照合しましたか？候補の育成状態や助っ人は別途確認が必要です。").setPositiveButton("照合済み",(d,w)->{try{repo.inventory.put("humanReconciled",true);repo.save();render();}catch(Exception e){error(e);}}).setNegativeButton("戻る",null).show();}catch(Exception e){error(e);}});
 }catch(Exception e){error(e);}}
 private void loadReviews(){reviews=new java.util.HashMap<>();reviewBundle=null;File f=new File(repo.root,"identity_review.json");if(!f.isFile())return;try{JSONObject b=new JSONObject(new String(java.nio.file.Files.readAllBytes(f.toPath()),java.nio.charset.StandardCharsets.UTF_8));reviews=InventoryReview.validate(b,repo.inventory);reviewBundle=b;}catch(Exception e){Toast.makeText(this,"保存した照合案を使えません："+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void search(){EditText field=new EditText(this);field.setSingleLine(true);field.setText(query);new AlertDialog.Builder(this).setTitle("番号・名前・#枠番号で検索").setView(field).setPositiveButton("検索",(d,w)->{query=InventorySearch.normalize(field.getText().toString());offset=0;render();}).setNeutralButton("解除",(d,w)->{query="";offset=0;render();}).setNegativeButton("閉じる",null).show();}
 private void showEvidence(int at){try{JSONObject item=repo.items.getJSONObject(at),review=reviews.get(item.getString("instanceId"));JSONArray evidence=item.optJSONArray("detailEvidence");if(evidence==null||evidence.length()==0)throw new Exception("詳細画像がまだありません");String path=review==null?evidence.getJSONObject(evidence.length()-1).getString("image"):review.getString("evidence");File file=new File(repo.root,path).getCanonicalFile();if(!file.toPath().startsWith(repo.root.getCanonicalFile().toPath())||!file.isFile())throw new Exception("詳細画像を開けません");Bitmap bitmap=BitmapFactory.decodeFile(file.getPath());if(bitmap==null)throw new Exception("詳細画像を読み込めません");ScrollView scroll=new ScrollView(this);ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setImageBitmap(bitmap);scroll.addView(image,new ScrollView.LayoutParams(-1,-2));new AlertDialog.Builder(this).setTitle("#"+(at+1)+" 保存時の詳細（上下スクロール）").setView(scroll).setPositiveButton("閉じる",null).show();}catch(Exception e){error(e);}}
 private void importReview(Intent data){try(InputStream in=getContentResolver().openInputStream(data.getData())){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))>0){if(out.size()+n>4_000_000)throw new IOException("照合JSONは4MB以下");out.write(buffer,0,n);}repo=new InventoryRepository(this);JSONObject clean=InventoryReview.sanitized(new JSONObject(out.toString("UTF-8")),repo.inventory);JSONArray rows=clean.getJSONArray("items");for(int i=0;i<rows.length();i++){File file=new File(repo.root,rows.getJSONObject(i).getString("evidence")).getCanonicalFile();if(!file.toPath().startsWith(repo.root.getCanonicalFile().toPath())||!file.isFile())throw new IOException("照合元の詳細画像が端末にありません");}File temp=new File(repo.root,"identity_review.json.tmp");try(FileOutputStream f=new FileOutputStream(temp)){f.write(clean.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));f.getFD().sync();}java.nio.file.Files.move(temp.toPath(),new File(repo.root,"identity_review.json").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);offset=0;render();new AlertDialog.Builder(this).setMessage(rows.length()+"枠の画像照合案を取り込みました。番号・名前の確定や編成決定は行っていません。").setPositiveButton("OK",null).show();}catch(Exception e){error(e);}}
 private void confirm(int at){LinearLayout fields=new LinearLayout(this);fields.setOrientation(android.widget.LinearLayout.VERTICAL);EditText id=new EditText(this);id.setHint("ゲーム詳細のNo.");id.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);EditText name=new EditText(this);name.setHint("正確な名前・進化形態");try{JSONObject item=repo.items.getJSONObject(at),review=reviews.get(item.getString("instanceId"));if(item.getJSONObject("recognition").optBoolean("userConfirmed")){id.setText(item.optString("monsterId"));name.setText(item.optString("name"));}else if(review!=null){id.setText(review.optString("monsterId"));if(!review.isNull("name"))name.setText(review.optString("name"));}}catch(Exception e){error(e);return;}fields.addView(id);fields.addView(name);new AlertDialog.Builder(this).setTitle("実際の詳細画面と照合").setView(fields).setPositiveButton("確認して保存",(d,w)->{try{repo.confirm(at,Integer.parseInt(id.getText().toString()),name.getText().toString());render();}catch(Exception e){error(e);}}).setNegativeButton("不明のまま",null).show();}
 private void calibrate(){android.content.SharedPreferences prefs=getSharedPreferences("pad_solver",0);LinearLayout box=new LinearLayout(this);box.setOrientation(android.widget.LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(box);String[] keys={"columns","expected","firstX","pitchX","top","bottom","pitchY","iconWidth"};String[] names={"列数","所持数（画面の実数）","先頭列中心X/幅","列間隔/幅","上端Y/高さ","下端Y/高さ","行間隔/高さ","アイコン幅/画面幅"};String[] defaults={"5","707","0.094","0.183","0.36","0.875","0.0874","0.145"};EditText[] fields=new EditText[8];for(int i=0;i<8;i++){TextView l=new TextView(this);l.setText(names[i]);box.addView(l);fields[i]=new EditText(this);fields[i].setInputType(8194);fields[i].setText(i<2?String.valueOf(prefs.getInt("box."+keys[i],Integer.parseInt(defaults[i]))):String.valueOf(prefs.getFloat("box."+keys[i],Float.parseFloat(defaults[i]))));box.addView(fields[i]);}CheckBox top=new CheckBox(this);top.setText("BOX先頭にいることを確認した");box.addView(top);CheckBox filters=new CheckBox(this);filters.setText("ALL・検索空欄・絞り込みなしを確認した");box.addView(filters);
 new AlertDialog.Builder(this).setTitle("BOXキャリブレーション（属性順可）").setView(scroll).setPositiveButton("保存",(d,w)->{try{android.content.SharedPreferences.Editor e=prefs.edit();for(int i=0;i<8;i++)if(i<2)e.putInt("box."+keys[i],Integer.parseInt(fields[i].getText().toString()));else e.putFloat("box."+keys[i],Float.parseFloat(fields[i].getText().toString()));e.putBoolean("box.topConfirmed",top.isChecked()).putBoolean("box.filtersConfirmed",filters.isChecked()).apply();new BoxCalibration(prefs).validate();Toast.makeText(this,"保存しました。BOXモードで画面共有を開始してください",Toast.LENGTH_LONG).show();}catch(Exception e){error(e);}}).setNegativeButton("閉じる",null).show();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;if(req==43){importReview(data);return;}if(req!=42)return;try(InputStream in=getContentResolver().openInputStream(data.getData())){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))>0){if(out.size()+n>8_000_000)throw new IOException("カタログは8MB以下");out.write(buffer,0,n);}JSONObject raw=new JSONObject(out.toString("UTF-8"));MonsterCatalogProvider.Local catalog=new MonsterCatalogProvider.Local(raw);repo.inventory.put("catalogVersion",catalog.getVersion());for(int i=0;i<repo.items.length();i++){JSONObject item=repo.items.getJSONObject(i);java.util.List<Integer> ids=catalog.identify(Long.parseUnsignedLong(item.getString("iconHash"),16));JSONArray candidates=new JSONArray();for(int id:ids)candidates.put(new JSONObject().put("monsterId",id).put("score",.5));item.getJSONObject("recognition").put("candidates",candidates);}try(FileOutputStream f=new FileOutputStream(new File(repo.root,"catalog_version.json"))){f.write(raw.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));}repo.save();render();}catch(Exception e){error(e);}}
 private void label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);root.addView(t);}private void button(String s,Runnable run){Button b=new Button(this);b.setText(s);root.addView(b);b.setOnClickListener(v->run.run());}private void error(Exception e){new AlertDialog.Builder(this).setMessage(e.getMessage()).setPositiveButton("OK",null).show();}
}
